//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZohoCRMApi_EnmascararEmails.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZohoCRMApi_EnmascararEmails.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1000.VDCIR6EWHUF066806Q59N11VK2LD9H.
        /// </summary>
        internal static string client_id_LD {
            get {
                return ResourceManager.GetString("client_id_LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1000.QBL8A7NQY2T4713PGNBIMB5O5ENTMX.
        /// </summary>
        internal static string client_id_QA {
            get {
                return ResourceManager.GetString("client_id_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dc2569f1311e05027ff25e1cb6a2dadbcc710d4376.
        /// </summary>
        internal static string client_secret_LD {
            get {
                return ResourceManager.GetString("client_secret_LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 05b7a33ecaaca112a8c9afd1bd85f02aa6a75a58ca.
        /// </summary>
        internal static string client_secret_QA {
            get {
                return ResourceManager.GetString("client_secret_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C:\\ZohoCRM_EmailsMasking.
        /// </summary>
        internal static string File_Local_Logs {
            get {
                return ResourceManager.GetString("File_Local_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string Mask_All {
            get {
                return ResourceManager.GetString("Mask_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string Prod {
            get {
                return ResourceManager.GetString("Prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.zoho.com.
        /// </summary>
        internal static string redirect_uri_LD {
            get {
                return ResourceManager.GetString("redirect_uri_LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.zoho.com.
        /// </summary>
        internal static string redirect_uri_QA {
            get {
                return ResourceManager.GetString("redirect_uri_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1000.5cb1f85d818b05190cb5c0a24cb72c76.8ab38462a543c65c1ca5a143c115dd2f.
        /// </summary>
        internal static string refresh_token_LD {
            get {
                return ResourceManager.GetString("refresh_token_LD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1000.f16bf6afe58706cb221f57cb0343c4af.cce67014031a3b0318683c1ba465b569.
        /// </summary>
        internal static string refresh_token_QA {
            get {
                return ResourceManager.GetString("refresh_token_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZohoCRM.modules.custom.all,ZohoCRM.modules.contacts.all,ZohoCRM.modules.accounts.all,ZohoCRM.modules.deals.all,ZohoCRM.modules.events.all,ZohoCRM.modules.tasks.all,ZohoCRM.modules.calls.all,ZohoCRM.modules.invoices.all,ZohoCRM.modules.pricebooks.all,ZohoCRM.modules.salesorders.all,ZohoCRM.modules.purchaseorders.all,ZohoCRM.modules.products.all,ZohoCRM.modules.cases.all,ZohoCRM.modules.solutions.all,ZohoCRM.modules.vendors.all,ZohoCRM.modules.quotes.all,ZohoCRM.modules.ALL,ZohoCRM.settings.ALL,ZohoCRM.users. [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
    }
}
